version: 0.2
#comment
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - dotnet run ./build/build.csproj

artifacts:
  files:
    - build/build_output/*
    - appspec.yml
    - installApp.sh
